version: 0.2
env:
  variables:
    DIST_FOLDER: "dist"
    BUILD_ENV: "dev"
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Install dependencies"
      - cd cdk
      - npm install
      - npm run build
  build:
    commands:
      - npx cdk synth -o out
artifacts:
  files:
    - cdk/out/*.template.json
    - buildspec.validation.yaml